// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas;

  Canvas = (function() {

    function Canvas(id, options) {
      this.id = id;
      this.options = options;
      this.w = this.options.width ? this.options.width : 400;
      this.h = this.options.height ? this.options.height : 400;
      this.canvas = document.createElement("canvas");
      this.canvas.width = this.w;
      this.canvas.height = this.h;
      this.canvas.id = this.id;
    }

    Canvas.prototype.attach = function(ancestor) {
      this.ancestor = ancestor;
      if (this.ancestor) {
        $('body').find("#" + this.ancestor).append($(this.canvas));
      } else {
        $('body').append($(this.canvas));
      }
      return this.ctx = this.canvas.getContext("2d");
    };

    Canvas.prototype.dimensions = function() {
      return [this.w, this.h];
    };

    Canvas.prototype.destroy = function() {
      $("#" + this.id).remove();
      return delete this;
    };

    return Canvas;

  })();

}).call(this);
