// Generated by CoffeeScript 1.3.3
(function() {
  var Particle;

  Particle = (function() {

    function Particle(x, y) {
      this.x = x;
      this.y = y;
    }

    Particle.prototype.move = function(x, y) {
      this.x = x;
      return this.y = y;
    };

    Particle.prototype.destroy = function() {
      return delete this;
    };

    return Particle;

  })();

}).call(this);
