// Generated by CoffeeScript 1.3.3
(function() {
  var Shape;

  Shape = (function() {

    function Shape(context, options) {
      this.context = context;
      this.options = options;
      this.loc = this.options.loc ? this.options.loc : new Particle(0, 0);
      this.color = this.options.color ? this.options.color : 'white';
      this.w = this.options.width ? this.options.width : 1;
      this.h = this.options.height ? this.options.height : 1;
    }

    Shape.prototype.move = function(point) {
      this.loc = point;
      return this.context.fillStyle = this.color;
    };

    Shape.prototype.destroy = function() {
      return delete this;
    };

    return Shape;

  })();

}).call(this);
